exports.Core = require('@uppy/core')
exports.Dashboard = require('@uppy/dashboard')
exports.Informer = require('@uppy/informer')
exports.StatusBar = require('@uppy/statusbar')
exports.ThumbnailGenerator = require('@uppy/thumbnail-generator')
exports.Tus = require('@uppy/tus')
